# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_auto_20160125_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='n_bookmarks',
            field=models.IntegerField(verbose_name='Bookmarks'),
        ),
    ]
