# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 05:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dailyhn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='entry',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='entry',
            field=models.ManyToManyField(to='dailyhn.Entry'),
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ManyToManyField(default='nikola', editable=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
