# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyhn', '0002_auto_20160128_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='entry',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailyhn.Entry'),
        ),
    ]
