# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyhn', '0002_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('points', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('n_bookmarks', models.IntegerField(verbose_name='Bookmarks')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.DeleteModel(
            name='SavedEmbed',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='entry',
            field=models.ManyToManyField(to='dailyhn.Entry'),
        ),
    ]
