# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyhn', '0003_auto_20160128_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='url',
            new_name='article_url',
        ),
        migrations.AddField(
            model_name='entry',
            name='comment_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
