# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyhn', '0004_bookmark_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ManyToManyField(default='nikola', to=settings.AUTH_USER_MODEL),
        ),
    ]
