# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyhn', '0004_auto_20160128_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='star',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='entry',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
