# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 07:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dailyhn', '0006_auto_20160129_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='updated',
            field=models.DateTimeField(auto_now=True),
            preserve_default=False,
        ),
    ]
