# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyhn', '0007_bookmark_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
