# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 15:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_countries.fields
import fontawesome.fields


class Migration(migrations.Migration):

    replaces = [('user', '0001_initial'), ('user', '0002_profile_age'), ('user', '0003_auto_20160202_1758'), ('user', '0004_auto_20160204_0735'), ('user', '0005_auto_20160204_0802'), ('user', '0006_auto_20160204_0813'), ('user', '0007_auto_20160204_0815'), ('user', '0008_auto_20160204_0819'), ('user', '0009_auto_20160205_1950'), ('user', '0010_auto_20160206_1816'), ('user', '0011_userprofile_icon'), ('user', '0012_auto_20160208_2208')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created', models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 4, 0, 35, 5, 902780, tzinfo=utc))),
                ('days_at_homepage', models.IntegerField(default=3)),
                ('entries_per_day', models.IntegerField(default=10)),
                ('updated', models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 4, 0, 35, 21, 607963, tzinfo=utc))),
                ('icon_bookmark', models.ImageField(blank=True, null=True, upload_to='icon_bookmark/%Y/%m/%d')),
                ('icon_symbol', models.ImageField(blank=True, null=True, upload_to='icon_symbol/%Y/%m/%d')),
                ('icon', fontawesome.fields.IconField(blank=True, max_length=60)),
            ],
        ),
    ]
