# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.CharField(default=20, max_length=100),
            preserve_default=False,
        ),
    ]
