# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 00:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20160202_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bookmark_icon',
            field=models.ImageField(blank=True, null=True, upload_to='bookmark_icon/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 4, 0, 35, 5, 902780, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='days_at_homepage',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='entries_per_day',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 4, 0, 35, 21, 607963, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
