# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20160204_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bookmark_icon',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='icon_bookmark',
            field=models.ImageField(blank=True, null=True, upload_to='icon_bookmark/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='icon_symbol',
            field=models.ImageField(blank=True, null=True, upload_to='icon_symbol/%Y/%m/%d'),
        ),
    ]
