# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20160204_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='icon_bookmark',
            field=models.ImageField(blank=True, null=True, upload_to='icon_bookmark/%Y/%m/%d', width_field='32'),
        ),
    ]
