# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 15:06
from __future__ import unicode_literals

from django.db import migrations
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20160206_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='icon',
            field=fontawesome.fields.IconField(blank=True, default='star', max_length=60),
        ),
    ]
